version: '3.8'
services:
  postgres:
    image: postgres:17
    container_name: dashboard-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: dashboard
    ports:
      - "5432:5432"
